name: Deploy to Dev Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Чекаут кода
      - name: Checkout code
        uses: actions/checkout@v4

      # Добавление known_hosts
      - name: Add known_hosts
        run: |
          ssh-keyscan -H 141.95.17.102 >> ~/.ssh/known_hosts

      # Установка SSH ключа
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.secret_working_key }}
          known_hosts: unnecessary

      # Деплой на сервер
      - name: Deploy to Server
        run: |
          ssh ubuntu@141.95.17.102 '
            cd /home/ubuntu/unie-admin &&
            git pull origin master || { echo "Git pull failed"; exit 1; }
          '
